Домашнее задание: верстка
htmlacademy-htmlcss/1841097-device-32 pull request #2
Opened 2021-09-27 16:30 UTC by vv16vv

2021-09-28 06:58 UTC, Kanasimy requested changes
Комментарии ниже по коду, и комменты не команда к действию, а в основном моя точка зрения.  С ней можно согласится, а можно и не соглашатся. Фактических ошибок в целом нет и работа супер. Пожалуй одно у меня вызывает вопросы - это обилие input type checkbox,radio для переключений. Это где так учат, возможно я что-то пропустила ) Верстку  декаративных элементов вам еще будут рассказывать. 
Что сейчас можно поправить - это структуру слайда, кнопки переключения слайда в каждом слайде точно ни к чему. Все остальное можно оставить на потом, и когда будут про это рассказывать, тогда и поправить

2021-09-28 06:58 UTC, Kanasimy commented on index.html
> +      </label>
не думаю что это предполагается нажимать, скорее декоративный элемент.  в стайлгайде нет этого элемента и поэтому непонятно как чекбокс будет в неактивном состоянии выглядеть

2021-09-28 06:58 UTC, Kanasimy commented on catalog.html
> +      </fieldset>
Опять забегаешь вперед, про такой бегунок и как его сверстать будут рассказывать. Это касается и чекбоксов и радио

2021-09-28 14:08 UTC, vv16vv commented on index.html
> -    <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>
Все в порядке! Эта строка была в заготовке проекта при создании и была удалена - она же показана красным.

2021-09-28 14:31 UTC, vv16vv commented on index.html
> +      <li class="header-navigation-user-menu-item header-navigation-search">
Спасибо! приму к сведению. А как было бы лучше тогда сверстать заголовок? Сначала я думала, что тут подошла бы сетка 2х2 - первая строка: поиск, прочие кнопки из пользовательского меню; вторая строка - каталог товаров, прочие кнопки. Но потом обратила внимание, что когда каталог развернут, его пункты подменю заезжают на вторую половину. В общем поэтому и остановилась на списках, ну и плюс потому что на лекции их показали :)

2021-09-28 14:51 UTC, vv16vv commented on index.html
> +      </label>
ага, спросила в дискорде - там тоже подтвердили, что это не чекбокс :( 
В общем поменяла на span.

2021-09-28 14:54 UTC, vv16vv commented on catalog.html
> +      </fieldset>
Это было на лекции почти в самом конце :) код прямо оттуда и скопирован и чуть-чуть подправлен.

2021-09-28 15:29 UTC, vv16vv commented
> Пожалуй одно у меня вызывает вопросы - это обилие input type checkbox,radio для переключений. Это где так учат, возможно я что-то пропустила )

Идея взята из тренажера "Мастерская: декоративные эффекты" шаги "Слайдер на CSS" с [20](https://htmlacademy.ru/courses/76/run/20) по [23](https://htmlacademy.ru/courses/76/run/23)

2021-09-29 06:27 UTC, Kanasimy commented on index.html
> +      <li class="header-navigation-user-menu-item header-navigation-search">
Я бы сделала две строки. Первая - > .search  + nav.user-nav Вторая - >nav.nav-main  Каталог действительно при исходных данных смысла отдельно верстать нет.

2021-09-29 06:32 UTC, Kanasimy commented on catalog.html
> +      </fieldset>
ок, посмотрела, действительно

2021-09-29 07:10 UTC, vv16vv commented on index.html
> +    <ul class="slider-list">
Переделала, вынесла блок переключателей за пределы списка слайдов и упростила. Остались одни кнопки.

2021-09-30 08:10 UTC, merged